export default {
  VERSION: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/latestupdate.json',
  FETCH_NEWS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/news.json',
  FETCH_QUICKSTATS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/quickstats.json',
  FETCH_PAGECONTENT_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/generalcontent.json',
  FETCH_REGIONS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/regions.json',
  FETCH_INITIATIVES_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/initiatives.json',
  GET_INDICATORS_BY_COUNTRIES_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/dataelements.json',
  GET_INITIATIVES_INDICATORS_BY_COUNTRIES_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/initiatives-dataelements.json',
  FETCH_CHART_DATA_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/chartdata.json',
  GET_INDICATORS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/indicators.json',
  GET_INDICATORS_BY_DATAELEMENTS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/mapdata.json',
  GET_INITIATIVES_INDICATORS_BY_DATAELEMENTS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/initiatives-mapdata.json',
  FETCH_KEYFACTS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/keyfacts.json',
  FETCH_TARGETANDPROGRESS_RECEIVED: 'https://who-malariatoolkit.adapptlabs.com/report/prod/v1/targets.json',
}
