import { createTypes } from 'reduxsauce'

export default createTypes(`
  START_SYNC
  SYNC_SUCCESS
  SYNC_FAILED
  SET_SYNC_MESSAGE

  CHECK_VERSION

  IMPORT_VERSION
  IMPORT_CONTENT_FROM_ASSETS
  
  FETCH_VERSION_REQUEST
  FETCH_VERSION_SUCCESS
  FETCH_VERSION_FAILURE
  
  FETCH_REQUEST
  FETCH_SUCCESS
  FETCH_FAILURE

  FETCH_VERSION_REQUEST
  FETCH_VERSION_SUCCESS
  FETCH_VERSION_FAILURE

  FETCH_NEWS_SUCCESS
  FETCH_CHART_DATA_SUCCESS
  FETCH_INITIATIVES_SUCCESS
  FETCH_GENERAL_CONTENT_SUCCESS
  FETCH_QUICK_STATS_SUCCESS
  FETCH_REGIONS_SUCCESS
  FETCH_DATA_ELEMENTS_SUCCESS
  FETCH_MAP_DATA_SUCCESS
  FETCH_INDICATORS_SUCCESS
  FETCH_INITIATIVES_DATA_ELEMENTS_SUCCESS
  FETCH_INITIATIVES_MAPDATA_SUCCESS
  FETCH_KEYFACTS_SUCCESS
  FETCH_TARGETANDPROGRESS_SUCCESS
  
  IMPORT_NEWS
  IMPORT_CHART_DATA
  IMPORT_INITIATIVES
  IMPORT_GENERAL_CONTENT
  IMPORT_QUICK_STATS
  IMPORT_REGIONS
  IMPORT_DATA_ELEMENTS
  IMPORT_MAP_DATA
  IMPORT_INDICATORS
  IMPORT_INITIATIVES_DATA_ELEMENTS
  IMPORT_INITIATIVES_MAP_DATA
  IMPORT_KEYFACTS
  IMPORT_TARGETANDPROGRESS

  SET_INDICATORS_BY_COUNTRIES
  ENABLE_MULTI_SELECT_COUNTRIES
  SELECT_COUNTRIES_REGION

  SET_INITIATIVE_INDICATOR_BY_COUNTRIES

  COMPARE_COUNTRIES_BY_REGION_INDICATOR
  SET_COMPARED_COUNTRIES_INDICATORS

  SET_INDICATOR_DATA_ELEMENT_COUNTRIES_LIST

  GENERATE_MAP_DATA_WITH_DATA_ELEMENT
  SET_GENERATED_MAP_DATA
  GENERATE_INITIATIVE_MAP
  SET_GENERATED_INITIATIVE_MAP_DATA

  COMPARE_COUNTRIES_BY_INITIATIVE_INDICATOR
  SET_COMPARED_COUNTRIES_INITIATIVE_INDICATORS
`, {});